### ISSUE TITLE
可以把node js 和angular js的部署文档写一下吗？

### ISSUE THREAD

**Issue by lqq-cb** [zhangxd1989/springboot-dubbox-web#1]
可以把node js 和angular js的部署文档写一下吗？，把代码clone了，不知道怎么本地跑起来啊，刚入门的，看到你的代码，觉得好，想自己学习一下你的代码，不知道怎么跑起来那个app.js

**Comment by zhangxd1989** [comment]
node js 安装可以参考官网（https://nodejs.org/en/）
项目的运行流程在readme的最下方有说明

**Comment by NathanPelli** [comment]
启动不了，报错啊。整半天找不到原因，楼主你本地可以起来吗？？
