### ISSUE TITLE
哥哥，你的dubbox2.8.4jar没有啊

### ISSUE THREAD

**Issue by lqq-cb** [zhangxd1989/springboot-dubbox-web#2]
maven仓库没这个，当当没放上去。我自己本地仓库搞了一个，依赖改成
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dubbo</artifactId>
                <version>C:\Users\alai\.m2\repository\com\alibaba\dubbo\2.8.4\dubbo.jar</version>
            </dependency>，也不行啊。哥哥，你找个时间回复一下疑问，谢谢。

**Comment by zhangxd1989** [comment]
把当当的dubbox 使用maven install到本地库或者可以deploy到私服
