### ISSUE TITLE
请问这个web系统的用户名密码是多少呢？

### ISSUE THREAD

**Issue by andyChenHuaYing** [zhangxd1989/springboot-dubbox-web#3]
请问楼主，如题。另外请教一下，这个项目的后端是不是zhangxd1989/springboot-dubbox 这里所对应的platform-admin-web 提供的后台服务呢？希望楼主看到回复下，谢谢！！！

**Comment by zhangxd1989** [comment]
@andyChenHuaYing 是platform-admin-web这个项目，管理员账号是admin，密码是admin
